repos:
- repo: https://github.com/nicklockwood/SwiftFormat
  rev: 0.57.2
  hooks:
  - id: swiftformat
    stages: [pre-commit]
- repo: https://github.com/realm/SwiftLint
  rev: 0.59.1
  hooks:
    - id: swiftlint
      args: [--fix]
      stages: [pre-commit]
- repo: local
  hooks:
    - id: make_generate_swiftlint_exclude
      name: Generate .swiftlint_excluded.generated.yml
      entry: make swiftlint_exclude
      stages: [post-checkout]
      language: system
      always_run: true

