install: setup gen
	$(call pretty_print, Serena is ready !)

setup:
	brew bundle
	mint bootstrap
	rm -rf .git/hooks
	pre-commit install --hook-type pre-commit --hook-type post-checkout

gen: swiftgen swiftlint_exclude

test-dict:
	swift run  --package-path ./JMdictTools jmdict-tools ./small-dict.xml -o sqlite

# Generate fonts, colors, l10n, images
swiftgen:
	$(call pretty_print, Generating swiftgen)
	@fd swiftgen.yml ./serena -t f -x \
		mint run swiftgen config run -q --config {}


# Swiftlint exclude helps it run faster instead of hopping over every generated file
swiftlint_exclude:
	$(call pretty_print, Generating .swiftlint_excluded.generated.yml)
	@( \
		echo "# DO NOT EDIT - This file is automatically generated from generate_swiftlint_exclude\nexcluded:" && \
		fd -H -t d -I '^(?:\.build|Generated)$$' | sort | \
		sed 's/^/  - /' \
	) > .swiftlint_excluded.generated.yml

.PHONY: install

define pretty_print
	@echo "\033[1;35m=== $(1) === \033[0m"
endef
